name: .NET Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x  # Use stable version to avoid known issues

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      env:
        MSBUILDDISABLETASKHOST: 1  # Disable problematic MSBuild task host
